global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'profile'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'profile:8080' ]
  - job_name: 'work'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'work:8090' ]
  - job_name: 'news'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'news:9000' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
