services:
  configserver:
    image: "configserver:s11"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      THC_PORT: 8071
      THC_PATH: /actuator/health

  eurekaserver:
    image: "eurekaserver:s11"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      THC_PORT: 8070
      THC_PATH: /actuator/health

  profile:
    image: "profile:s11"
    container_name: profile-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "profile"
      SPRING_PROFILES_ACTIVE: "prod"
      THC_PORT: 8080
      THC_PATH: /actuator/health
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  news:
    image: "news:s11"
    container_name: news-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "news"
      THC_PORT: 9000
      THC_PATH: /actuator/health
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  work:
    image: "work:s11"
    container_name: work-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "work"
      THC_PORT: 8090
      THC_PATH: /actuator/health
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "gatewayserver:s11"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      profile:
        condition: service_healthy
      work:
        condition: service_healthy
      news:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  lazar:
    driver: "bridge"
